model: RSMV2
inputDataS3Bucket: thetradedesk-mlplatform-us-east-1
subFolderKey: split
subFolderValue: Population
syntheticIdLength: 2000
audienceResultCoalesce: 4096
maxChunkRecordCount: 20480
paddingColumns: ZipSiteLevel_Seed,Targets,SyntheticIds,MatchedSegments,SampleWeights
populationOutputData3Path: data/prod/audience/RSMV2/Seed_None/v=1
inputDataS3Path: data/prod/audience/RSMV2/Imp_Seed_None/v=2
runDate: "{{ run_date.strftime('%Y-%m-%d') }}"
audienceJarBranch: master
audienceJarVersion: latest
