model: RSMV2
tag: Seed_None
version: 1
runDate: "{{ run_date.strftime('%Y-%m-%d') }}"
lookBack: 10
startDate: '2025-03-20'
oosDataS3Bucket: thetradedesk-mlplatform-us-east-1
oosDataS3Path: data/prod/audience/RSMV2/Seed_None/v=2
subFolderKey: mixedForward
subFolderValue: Calibration
oosProdDataS3Path: data/prod/audience/RSMV2/Seed_None/v=1
coalesceProdData: 'False'
audienceResultCoalesce: 4096
audienceJarBranch: master
audienceJarVersion: latest
